/**
 * Every image on the site, in one map.
 *
 * Entries with a local "/photos/…" src are the client's own workroom
 * photography (re-encoded, EXIF stripped). Entries still using `u(…)` are
 * licensed Unsplash stock placeholders, chosen against the imagery rules in
 * the plan (2.4) — swap them out the same way as new photos arrive. Curtain,
 * campervan and upholstery slots are now real; still stock: blinds, fabric
 * close-ups, garment work and the area pages.
 *
 * GRADE is applied to every remote image so stock from different photographers
 * reads as one consistent brand. Local photos are left ungraded.
 */

export type Img = {
  src: string;
  alt: string;
  /** Tiny inline JPEG used as the blur-up placeholder. */
  blurDataURL: string;
};

/** Slight desaturation, a touch of lift, softened contrast. */
const GRADE = "sat=-12&bri=4&con=-3";

const u = (id: string, w: number) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&q=80&w=${w}&${GRADE}`;

export const images = {
  heroPoster: {
    src: "/photos/workroom-machines.jpg",
    alt: "An industrial coverstitch machine on the workroom floor, sheers laid out on the tables behind",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAARAAoDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAABQAGB//EACkQAAIABAQDCQAAAAAAAAAAAAECAAMEIQUGETESYXETFTI1QVFzscH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAP/EABYRAQEBAAAAAAAAAAAAAAAAAAARAf/aAAwDAQACEQMRAD8AZr5kyVRhlKcTXCu+45CBu82FnxOUrDdSosfbaM3TYxOSo7N2Zio0BQ+v7CS5dxF1DkEFhro0+4684IaHy/53T/Kv3HRV8I6RRRaH/9k=",
  },
  workroom: {
    src: "/photos/workroom-floor.jpg",
    alt: "The workroom floor — cutting tables, machines and sheers in production",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAASAAoDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAQBBQYH/8QAJBAAAQMCBgIDAAAAAAAAAAAAAQIDEQAhBAUSIjFRBhNBQoH/xAAVAQEBAAAAAAAAAAAAAAAAAAACAf/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwDRtuoWoti8CY/aheYsJWUqcggwRNUeF8hytDqHPW2t5bcJ+dJ6PdxenTilEyE5dftgE0bFjnuJ2aNG2eYtNPoddLaSXF8D7GiikL//2Q==",
  },
  capCurtains: {
    src: "/photos/patterned-drapes.jpg",
    alt: "Patterned curtain panels made up and ready to hang",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwEF/8QAIBAAAgICAgIDAAAAAAAAAAAAAQIDEQAEITEFEhMiQf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFxEBAAMAAAAAAAAAAAAAAAAAAAECEf/aAAwDAQACEQMRAD8Ak3wIyTMn2kNuVPFkWaGIDqUPbahU/oN2MGLVG1NDE7kKW5rvjNUeM1wACisR2SO8nOHV/9k=",
  },
  capBlinds: {
    src: u("photo-1574197635162-68e4b468e4e9", 1200),
    alt: "Tall windows dressed with lined sheers in a bright room",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAdEAABBAIDAAAAAAAAAAAAAAABAAIDEQQTMTKx/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AKuMQ7AjPAtQZnHdJV9j6iIyP//Z",
  },
  capSoft: {
    src: "/photos/bench-cushions-ochre.jpg",
    alt: "A run of bench cushions in ochre, stacked in the workroom",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAIxAAAgECBQUBAAAAAAAAAAAAAQIDABIEBREhMQYUQXGRsf/EABUBAQEAAAAAAAAAAAAAAAAAAAQF/8QAGREAAwEBAQAAAAAAAAAAAAAAAQIDABFB/9oADAMBAAIRAxEAPwCzZ/NHFZFBEijwWJ98/laV6uFgvjwobTcatz8obMoO2xUqBrgGJ3osqSdbjU5Hr0hjnicz5v/Z",
  },
  capMarine: {
    src: "/photos/campervan-bed.jpg",
    alt: "A campervan fit-out with the bed made up across the rear",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIE/8QAHxAAAgIBBAMAAAAAAAAAAAAAAQIDBAAFERJhEyGR/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABYRAQEBAAAAAAAAAAAAAAAAAAEAAv/aAAwDAQACEQMRAD8AzR0KnnhFjUp2sMBwHA7dfMiTTHEjA3mYgndins94xgGmdyX/2Q==",
  },
  stepMeasure: {
    src: "/photos/cut-pieces-labelled.jpg",
    alt: "Cover panels cut, bundled and labelled from a client's templates",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQMFBv/EACQQAAEDBAEDBQAAAAAAAAAAAAECAxEABBIhBQYTJDFBYXGR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQEAAwAAAAAAAAAAAAAAAAABAAIR/9oADAMBAAIRAxEAPwBq7t1jwX2S9b3jodC2yAEhWhE+kH2+KKumX8zjet4zqUmYqHzTKrrj+OleKkFxsKidSkj8mtqwu47DeTjajiJJRs6+6nZ0IqmLP//Z",
  },
  stepCut: {
    src: "/photos/cutting-table.jpg",
    alt: "Upholstery vinyl and foam layered on the automated cutting table",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQQG/8QAHxAAAgIDAAIDAAAAAAAAAAAAAQIDEQAEIQUSQcHR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwT/xAAZEQEAAgMAAAAAAAAAAAAAAAABAAIDITH/2gAMAwEAAhEDEQA/AFRBovOmyux7MKIZTQIu/vExBDIocbbAN0DnMx+x4aNVJhnmjrlA2MlCbagKN2Shz5/claZaumIWHs//2Q==",
  },
  stepFinish: {
    src: "/photos/boucle-daybed.jpg",
    alt: "A finished bouclé bolster checked over by hand",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQYH/8QAJBAAAgEDAgYDAAAAAAAAAAAAAQMCAAQRBRITISIxMkFRgaH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFREBAQAAAAAAAAAAAAAAAAAAAHH/2gAMAwEAAhEDEQA/AHbjVmoW87wWR6V5+ccv2s4cqwLpl0HTYZHfIu8j7NV2qXeItEVgSmQCSc4z7x9UKu4Zw4+PYdoiipI//9k=",
  },
  stepInstall: {
    src: "/photos/curtain-track-hooks.jpg",
    alt: "Curtain hooks going onto the track during a fit-out",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACEQAQABAgUFAAAAAAAAAAAAAAECAAUDBBIhMREjUZHh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwCZKz3u3ShPLYuImHxplrh6+UwX+7AErZBTlJJ1rTOWYh3F38UXY20lBr//2Q==",
  },
  fabLinen: {
    src: u("photo-1686806372785-fcfe9efa9b70", 800),
    alt: "Natural linen, close up",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAFxABAAMAAAAAAAAAAAAAAAAAAAECEf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A09pT0Ejf/9k=",
  },
  fabVelvet: {
    src: u("photo-1528458909336-e7a0adfed0a5", 800),
    alt: "Cotton velvet, close up",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQF/8QAGRAAAwADAAAAAAAAAAAAAAAAAAECEzFR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AN66SnRNkXAAk//Z",
  },
  fabBlockout: {
    src: u("photo-1585314062340-f1a5a7c9328d", 800),
    alt: "Blockout lining, close up",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMF/8QAFxABAQEBAAAAAAAAAAAAAAAAABECIf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8Ax8yJ8AR//9k=",
  },
  fabSheer: {
    src: u("photo-1594734415578-00fc9540929b", 800),
    alt: "Sheer voile, close up",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEG/8QAGxAAAwACAwAAAAAAAAAAAAAAAAECAzEREiH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A0tR0UpPzbIqx8aYAH//Z",
  },
  fabCanvas: {
    src: u("photo-1686806374120-e7ae3f19801d", 800),
    alt: "Cotton canvas, close up",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAVEAEBAAAAAAAAAAAAAAAAAAAAEf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AoqUEjf/Z",
  },
  fabOutdoor: {
    src: u("photo-1599568723850-14196ee0f991", 800),
    alt: "Outdoor-grade fabric in ochre, close up",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAdEAABBAIDAAAAAAAAAAAAAAABAAIDEQQxEhNh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCXHlPLOEjaN7CGGyT2b8RECt//2Q==",
  },
  fabWool: {
    src: u("photo-1528459061998-56fd57ad86e3", 800),
    alt: "Wool blend in eucalypt green, close up",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQF/8QAGBABAQADAAAAAAAAAAAAAAAAAQACETH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AM1BwdUr2SUP/9k=",
  },
  fabIndigo: {
    src: u("photo-1629197521865-4946b4acd2b0", 800),
    alt: "Velvet in deep indigo, close up",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAVEAEBAAAAAAAAAAAAAAAAAAAAEf/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AnKUFQX//2Q==",
  },
  productionFloor: {
    src: "/photos/auto-sewing-cell.jpg",
    alt: "A programmable sewing cell running on the production floor",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIFBv/EACEQAAIBBAICAwAAAAAAAAAAAAECEQADBBIFIQYxExQi/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAWEQEBAQAAAAAAAAAAAAAAAAABABH/2gAMAwEAAhEDEQA/AE5VXGoyi9wnvRFEGPUdweqEFtkVvgviQDBVRFRPHRcy+WtY4uFLJJKof1oI2gd1v15DRQv1MYwIkp7qYE1b/9k=",
  },
  projectMain: {
    src: "/photos/armchair-chinoiserie.jpg",
    alt: "An armchair reupholstered in a navy chinoiserie weave with a gold velvet seat cushion",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIE/8QAJBAAAgEDAgYDAAAAAAAAAAAAAQIDAAQRBTESISIyQeFRUnH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAAQAC/9oADAMBAAIRAxEAPwBnvdTit3JgLtEO+UBiQOePdSuutwjCLt9PdDeRTwtI0N3KmCfO5rfDptk0EbNG+SoJ6h8flGspIjf/2Q==",
  },
  projectDetail1: {
    src: "/photos/armchair-detail.jpg",
    alt: "The piped velvet seat cushion and chinoiserie arms, close up",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgQF/8QAIhAAAgICAgAHAAAAAAAAAAAAAQMCEQAhBSITFDNRYaHR/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABgRAQADAQAAAAAAAAAAAAAAAAEAAkFC/9oADAMBAAIRAxEAPwBcxcoM8ukrSmNQ3RMhdmvbeQqizwodXDqNdfzNnkUzSwqLIsW0XU4bAPyMYgqvSj94GtuohMn/2Q==",
  },
  projectDetail2: {
    src: "/photos/boucle-panels.jpg",
    alt: "Bouclé cover panels cut and matched on the bench",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAIG/8QAIBAAAgICAgIDAAAAAAAAAAAAAQIDBAARBRIxQQYhYf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwAbyzQcuTBMytsMrA+M0K80GUM1BHYjZYSEdv3XrFVvitdLMNtbMpMbhurKD296y5+BpvYkcAr2cnQ8D7ybB//Z",
  },
  projectDetail3: {
    src: "/photos/boucle-cutting.jpg",
    alt: "Bouclé panels laid out on the cutting table",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBv/EACMQAAIBBAEDBQAAAAAAAAAAAAECAwAEBREhBhPRIjFicZP/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABcRAQEBAQAAAAAAAAAAAAAAAAEAERL/2gAMAwEAAhEDEQA/ABMtlHvo423dgsVXaabfxYDiqg0NwBO0kitL6yolbgnnXvSM/m7zFP3I3MijgK7t5+qyx6xviTu0svyPmoHUdL//2Q==",
  },
  work01: {
    src: "/photos/chairs-black.jpg",
    alt: "Dining chairs finished in black leather",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQQFBv/EACUQAAIBAwMCBwAAAAAAAAAAAAECAwAEBRESEyGBIiQxMkFCUf/EABQBAQAAAAAAAAAAAAAAAAAAAAH/xAAXEQEAAwAAAAAAAAAAAAAAAAAAAREh/9oADAMBAAIRAxEAPwBa4y0Osi32L5EYhgrLuBYfh796C5C3Kgph7XaR01UelXp8PE+SjlErrv18PwOtaWGzteFPLw+0fQUYbl//2Q==",
  },
  work02: {
    src: "/photos/seats-blush.jpg",
    alt: "A run of moulded seat shells covered in blush leather",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAA//EACUQAAIBAwIFBQAAAAAAAAAAAAECAwAEESFBBQYSE3EVFjGB0f/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAGREBAAIDAAAAAAAAAAAAAAAAAQARAiFB/9oADAMBAAIRAxEAPwB7jg1/OFZLkuofqImjRsjzgNpR+3pzr3Lc53EJpjzBcpIIljjK/ALDJH3vTety7pr5H5QW9kLibpn/2Q==",
  },
  work03: {
    src: "/photos/stool-grey.jpg",
    alt: "A counter stool upholstered in slate grey leather",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAWAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBf/EACUQAAIBAwMCBwAAAAAAAAAAAAECAwAEEQUSIVGBFTEyQWFx0f/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQEBAQEAAAAAAAAAAAAAAAABAAIR/9oADAMBAAIRAxEAPwCC8kg066kiuQbhgeWI57/NPRN6Bl0+FlYZBCPyOvqoufCr64nlnlQPMxJ3nBX6z5VRFLp8MSRC+4RQoy3TtQTszSTLGdhCU2qRuYcj23H9rLa2ErGRsZc7j3oopwv/2Q==",
  },
  work04: {
    src: "/photos/banquette-frame.jpg",
    alt: "A banquette frame foamed up and ready for its cover",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwX/xAAeEAACAgMBAAMAAAAAAAAAAAABAwIRAAQhBZGx0f/EABUBAQEAAAAAAAAAAAAAAAAAAAED/8QAGREAAwEBAQAAAAAAAAAAAAAAAQIRAAMS/9oADAMBAAIRAxEAPwBvP2Jbj9ps1sWGSE7EyA0G+8r4xyPOiTGSkAjhu/3JO/quV7BVrbr0JZCM5LgaF3k9upMumS2BuR6V9+8Q4kmi3NyxPqDf/9k=",
  },
  work05: {
    src: "/photos/pleating-machine.jpg",
    alt: "Header tape feeding through the pleating machine",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAJRAAAQQBAwIHAAAAAAAAAAAAAQIDBBEhAAYxBRMSFSIjQVFy/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwA0aO01A8T7DTzwsleHTR4PNYrWkzuOmGx27pIya+v1okKO11bc86LbrCLKx21D00lIoCqHJ1TyyM37akBZTgqUMqr5OhSj/9k=",
  },
  work06: {
    src: "/photos/van-curtain.jpg",
    alt: "A blockout curtain fitted in a campervan window",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgQF/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDEQAEBRITMQYhI0FRsf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAXEQEAAwAAAAAAAAAAAAAAAAAAAQIR/9oADAMBAAIRAxEAPwBt2jmU6dXeuPHcQlRQ2iNA0/tYybdopB3VGR8oYXJ3DOMes0nxuCO/qeYqxt6WkEpHAorYWH//2Q==",
  },
  work07: {
    src: "/photos/van-cushions.jpg",
    alt: "Fitted cushions in a campervan interior",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAP/xAAhEAABBAEDBQAAAAAAAAAAAAABAAIDBBQREiExUWGj0f/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAZEQACAwEAAAAAAAAAAAAAAAABAgADERL/2gAMAwEAAhEDEQA/AIxW7wgMMLm6Vm7C4gOLu3XwrZNs85Hrb8REe0ctgiaQGXTP/9k=",
  },
  work08: {
    src: "/photos/auto-pleater.jpg",
    alt: "The automated pleating machine mid-run",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIFBv/EACIQAAEDBAEFAQAAAAAAAAAAAAECAxEABAUSMRMUISJBUf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFREBAQAAAAAAAAAAAAAAAAAAADH/2gAMAwEAAhEDEQA/AFyIUIFxs4T51QBB/PtCA2UJPReEjgwKk4Pe5yLbIXq0SSlJ9tREwK2ab3VIT2zBgRJTzUg//9k=",
  },
  work09: {
    src: "/photos/curtain-workroom.jpg",
    alt: "Sheers in production across the curtain workroom",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAASAAoDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAgb/xAAhEAACAQMEAwEAAAAAAAAAAAABAhEAAwQSITFRIkGBBf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ALqXFYlOYEx9rLZ9lWKs8EGDUnH/AHMBbiPoRrjpC+4PR+0ycgkk6MLfu0CakHF3/HTp2nmPdNrduFR5tx3RRVH/2Q==",
  },
  work10: {
    src: "/photos/banquette-dining.jpg",
    alt: "A channel-stitched leather banquette in a finished dining fit-out",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAJAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAUG/8QAIRAAAgEDAwUAAAAAAAAAAAAAAQIAAwURBCFBMTRRcdH/xAAUAQEAAAAAAAAAAAAAAAAAAAAE/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAECAxH/2gAMAwEAAhEDEQA/AKL3OgUfTMH3Uq2NuvjmNp3HFNQEfAA4H2YZe+b1Hwl6OXwVOapH/9k=",
  },
  svcCurtainsHero: {
    src: "/photos/curtain-workroom.jpg",
    alt: "The curtain workroom in production, sheers on the line",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAASAAoDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAgb/xAAhEAACAQMEAwEAAAAAAAAAAAABAhEAAwQSITFRIkGBBf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ALqXFYlOYEx9rLZ9lWKs8EGDUnH/AHMBbiPoRrjpC+4PR+0ycgkk6MLfu0CakHF3/HTp2nmPdNrduFR5tx3RRVH/2Q==",
  },
  svcCurtains1: {
    src: "/photos/curtain-machine.jpg",
    alt: "An industrial curtain machine running a long hem",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAARAAoDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAABQAEBv/EACYQAAIBAwMBCQAAAAAAAAAAAAECAAMEEQUhMXESFTI1UXOBkbH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwBW9d6VqGUrluFZuR0hXeDDZr+mrDkEDY/UBoapUSt2GJYjYFfWb10O+dQxBGRnDVt/mSFGaJ5rR9xf2dwvhHSUpR//2Q==",
  },
  svcCurtains2: {
    src: "/photos/patterned-drapes.jpg",
    alt: "Patterned curtain panels made up and ready to hang",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwEF/8QAIBAAAgICAgIDAAAAAAAAAAAAAQIDEQAEITEFEhMiQf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFxEBAAMAAAAAAAAAAAAAAAAAAAECEf/aAAwDAQACEQMRAD8Ak3wIyTMn2kNuVPFkWaGIDqUPbahU/oN2MGLVG1NDE7kKW5rvjNUeM1wACisR2SO8nOHV/9k=",
  },
  svcCurtains3: {
    src: "/photos/curtain-station.jpg",
    alt: "A programmable curtain station on the workroom floor",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAP/xAAlEAACAgEDAQkAAAAAAAAAAAABAwIRIQAEMQUGEhMVIjNBYdH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwA6ELVsxJqVtaLJn7hr4PNaerrtKgPDJqI5I/dG2iF9S7Qbvb2xMLMx3JDFCOAKxydU8vRD0mImY4MiMn71NL//2Q==",
  },
  svcCurtains4: {
    src: "/photos/auto-pleater.jpg",
    alt: "The automated pleating machine mid-run",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIFBv/EACIQAAEDBAEFAQAAAAAAAAAAAAECAxEABAUSMRMUISJBUf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFREBAQAAAAAAAAAAAAAAAAAAADH/2gAMAwEAAhEDEQA/AFyIUIFxs4T51QBB/PtCA2UJPReEjgwKk4Pe5yLbIXq0SSlJ9tREwK2ab3VIT2zBgRJTzUg//9k=",
  },
  svcSoftHero: {
    src: "/photos/armchair-chinoiserie.jpg",
    alt: "An armchair reupholstered in a navy chinoiserie weave with a gold velvet seat cushion",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIE/8QAJBAAAgEDAgYDAAAAAAAAAAAAAQIDAAQRBTESISIyQeFRUnH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAAQAC/9oADAMBAAIRAxEAPwBnvdTit3JgLtEO+UBiQOePdSuutwjCLt9PdDeRTwtI0N3KmCfO5rfDptk0EbNG+SoJ6h8flGspIjf/2Q==",
  },
  svcSoft1: {
    src: "/photos/bench-cushions-ochre.jpg",
    alt: "A run of bench cushions in ochre, stacked in the workroom",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQME/8QAIxAAAgECBQUBAAAAAAAAAAAAAQIDABIEBREhMQYUQXGRsf/EABUBAQEAAAAAAAAAAAAAAAAAAAQF/8QAGREAAwEBAQAAAAAAAAAAAAAAAQIDABFB/9oADAMBAAIRAxEAPwCzZ/NHFZFBEijwWJ98/laV6uFgvjwobTcatz8obMoO2xUqBrgGJ3osqSdbjU5Hr0hjnicz5v/Z",
  },
  svcSoft2: {
    src: "/photos/velvet-ottomans.jpg",
    alt: "Fringed velvet ottomans beside a leather armchair",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAIF/8QAIhAAAgECBgMBAAAAAAAAAAAAAQIDABEEBRITMUEVI2Fi/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABgRAAMBAQAAAAAAAAAAAAAAAAABETFR/9oADAMBAAIRAxEAPwCMzxG1q2pHhlVQbki1zyR3QvMSdQM36DuQfvNbMmEhlaCcr7dNi3NHbIstdixwq3Y3NiRQ3otSxH//2Q==",
  },
  svcSoft3: {
    src: "/photos/banquette-leather.jpg",
    alt: "A channel-stitched banquette in tan leather",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgQF/8QAJBAAAQIFAgcAAAAAAAAAAAAAAQACAwQFESESEwYxNJGhouH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAGREBAAIDAAAAAAAAAAAAAAAAAQACESIx/9oADAMBAAIRAxEAPwC1nEG7MMhCWA1utfUceE1ixarAa+7ZLIyDvHn2QNfN+n9/iKmTsW4LqT//2Q==",
  },
  svcSoft4: {
    src: "/photos/boucle-daybed.jpg",
    alt: "A bouclé bolster on a finished daybed",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQYH/8QAJBAAAgEDAgYDAAAAAAAAAAAAAQMCAAQRBRITISIxMkFRgaH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFREBAQAAAAAAAAAAAAAAAAAAAHH/2gAMAwEAAhEDEQA/AHbjVmoW87wWR6V5+ccv2s4cqwLpl0HTYZHfIu8j7NV2qXeItEVgSmQCSc4z7x9UKu4Zw4+PYdoiipI//9k=",
  },
  svcMarineHero: {
    src: "/photos/campervan-bed.jpg",
    alt: "A campervan fit-out with the bed made up across the rear",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIE/8QAHxAAAgIBBAMAAAAAAAAAAAAAAQIDBAAFERJhEyGR/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABYRAQEBAAAAAAAAAAAAAAAAAAEAAv/aAAwDAQACEQMRAD8AzR0KnnhFjUp2sMBwHA7dfMiTTHEjA3mYgndins94xgGmdyX/2Q==",
  },
  svcMarine1: {
    src: "/photos/van-squabs-stack.jpg",
    alt: "A stack of cut foam squabs ready for covering",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIG/8QAHRAAAgIDAAMAAAAAAAAAAAAAAQIAAwQFERIUMf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAECEf/aAAwDAQACEQMRAD8AmmrcZmTZkBxXVY3moNneA/JoEyNqqKp9UkADvDESLpjw/9k=",
  },
  svcMarine2: {
    src: "/photos/van-curtain.jpg",
    alt: "A blockout curtain fitted in a campervan window",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgQF/8QAIxAAAQMDAwUBAAAAAAAAAAAAAQIDEQAEBRITMQYhI0FRsf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAXEQEAAwAAAAAAAAAAAAAAAAAAAQIR/9oADAMBAAIRAxEAPwBt2jmU6dXeuPHcQlRQ2iNA0/tYybdopB3VGR8oYXJ3DOMes0nxuCO/qeYqxt6WkEpHAorYWH//2Q==",
  },
  svcMarine3: {
    src: "/photos/van-window-cover.jpg",
    alt: "An insulated window cover upholstered to template",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAEF/8QAJBAAAgEDAwMFAAAAAAAAAAAAAQIDAAQRBRIhEyIxQVFxkfD/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwBjTNbXDJMzBX7kmTnI+DwR7ioYL1zuS+XaeRgEDH1QLfUWbRN8sSSmNQybvQ5x+FYDaxfMxbrtyc+akK//2Q==",
  },
  svcMarine4: {
    src: "/photos/van-cushions.jpg",
    alt: "Fitted cushions in a campervan interior",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAP/xAAhEAABBAEDBQAAAAAAAAAAAAABAAIDBBQREiExUWGj0f/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAZEQACAwEAAAAAAAAAAAAAAAABAgADERL/2gAMAwEAAhEDEQA/AIxW7wgMMLm6Vm7C4gOLu3XwrZNs85Hrb8REe0ctgiaQGXTP/9k=",
  },
  svcGarmentHero: {
    src: u("photo-1739117441029-9f2a8e59e8b2", 1800),
    alt: "Hands guiding a panel under an industrial needle",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAME/8QAHBABAAICAwEAAAAAAAAAAAAAAQACBBEDBTFR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCOJh0OHbdVPkyW6kbLv1iIpf/Z",
  },
  svcGarment1: {
    src: u("photo-1673201229733-69d19c5c4a87", 1000),
    alt: "A machinist running a seam on striped fabric",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMF/8QAHRAAAgIBBQAAAAAAAAAAAAAAAQIAAwQFERQiQf/EABUBAQEAAAAAAAAAAAAAAAAAAAAC/8QAFREBAQAAAAAAAAAAAAAAAAAAAAH/2gAMAwEAAhEDEQA/ANbVs3Dw7VptVu6+SKccopCnYiIlQf/Z",
  },
  svcGarment2: {
    src: u("photo-1526290766257-c015850e4629", 1000),
    alt: "An industrial machine mid-run, close up",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEC/8QAHRAAAQQCAwAAAAAAAAAAAAAAAAECAwQSURETkf/EABQBAQAAAAAAAAAAAAAAAAAAAAH/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCJaZJgytHjvk317cngAB//2Q==",
  },
  svcGarment3: {
    src: u("photo-1673201230644-10baaee14e6b", 1000),
    alt: "Thread cones beside a bundled production run",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMF/8QAHhAAAgIBBQEAAAAAAAAAAAAAAQIAAwQFETFRouH/xAAVAQEBAAAAAAAAAAAAAAAAAAABA//EABcRAQADAAAAAAAAAAAAAAAAAAABESH/2gAMAwEAAhEDEQA/AIaTbkOHqqvCoD1NPZhzlefkRBS8h//Z",
  },
  svcGarment4: {
    src: u("photo-1684259499086-93cb3e555803", 1000),
    alt: "A production bench part-way through a run",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAID/8QAHxAAAAYCAwEAAAAAAAAAAAAAAAECAxESBEETFCJh/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABYRAQEBAAAAAAAAAAAAAAAAAAEAEf/aAAwDAQACEQMRAD8AkmW0ccY9mqxVS/pjDrnrEbjXoABaygZf/9k=",
  },
  svcProductionHero: {
    src: "/photos/auto-sewing-cell.jpg",
    alt: "A programmable sewing cell on the production floor",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIFBv/EACEQAAIBBAICAwAAAAAAAAAAAAECEQADBBIFIQYxExQi/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAWEQEBAQAAAAAAAAAAAAAAAAABABH/2gAMAwEAAhEDEQA/AE5VXGoyi9wnvRFEGPUdweqEFtkVvgviQDBVRFRPHRcy+WtY4uFLJJKof1oI2gd1v15DRQv1MYwIkp7qYE1b/9k=",
  },
  svcProduction1: {
    src: "/photos/cutting-table.jpg",
    alt: "The automated cutting table loaded with vinyl and foam",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQQG/8QAHxAAAgIDAAIDAAAAAAAAAAAAAQIDEQAEIQUSQcHR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwT/xAAZEQEAAgMAAAAAAAAAAAAAAAABAAIDITH/2gAMAwEAAhEDEQA/AFRBovOmyux7MKIZTQIu/vExBDIocbbAN0DnMx+x4aNVJhnmjrlA2MlCbagKN2Shz5/claZaumIWHs//2Q==",
  },
  svcProduction2: {
    src: "/photos/cut-pieces-labelled.jpg",
    alt: "Cut panels bundled and labelled for a production run",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQMFBv/EACQQAAEDBAEDBQAAAAAAAAAAAAECAxEABBIhBQYTJDFBYXGR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQEAAwAAAAAAAAAAAAAAAAABAAIR/9oADAMBAAIRAxEAPwBq7t1jwX2S9b3jodC2yAEhWhE+kH2+KKumX8zjet4zqUmYqHzTKrrj+OleKkFxsKidSkj8mtqwu47DeTjajiJJRs6+6nZ0IqmLP//Z",
  },
  svcProduction3: {
    src: "/photos/pleating-machine.jpg",
    alt: "Header tape feeding through the pleating machine",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAJRAAAQQBAwIHAAAAAAAAAAAAAQIDBBEhAAYxBRMSFSIjQVFy/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwA0aO01A8T7DTzwsleHTR4PNYrWkzuOmGx27pIya+v1okKO11bc86LbrCLKx21D00lIoCqHJ1TyyM37akBZTgqUMqr5OhSj/9k=",
  },
  svcProduction4: {
    src: "/photos/banquette-frame.jpg",
    alt: "A banquette frame foamed up on the workroom trolley",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAANAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwX/xAAeEAACAgMBAAMAAAAAAAAAAAABAwIRAAQhBZGx0f/EABUBAQEAAAAAAAAAAAAAAAAAAAED/8QAGREAAwEBAQAAAAAAAAAAAAAAAQIRAAMS/9oADAMBAAIRAxEAPwBvP2Jbj9ps1sWGSE7EyA0G+8r4xyPOiTGSkAjhu/3JO/quV7BVrbr0JZCM5LgaF3k9upMumS2BuR6V9+8Q4kmi3NyxPqDf/9k=",
  },
  areaPenrith: {
    src: u("photo-1628923139231-55ad0aa6bac7", 1600),
    alt: "A Penrith living room with timber floors and layered furnishings",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEE/8QAGxAAAwACAwAAAAAAAAAAAAAAAAECAyEEIpH/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwC8e1cSlvbNSx00uq9AJnX/2Q==",
  },
  areaBlacktown: {
    src: u("photo-1600493505873-cddd69453072", 1600),
    alt: "A Blacktown lounge room with upholstered seating and cushions",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIF/8QAGhAAAwEAAwAAAAAAAAAAAAAAAAECAwQRIv/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A1J5VvZOV5ot6z2wCZv/Z",
  },
  areaParramatta: {
    src: u("photo-1684928365257-13121f2742ef", 1600),
    alt: "A Parramatta apartment dining space with a city outlook",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAME/8QAHRAAAgIBBQAAAAAAAAAAAAAAAAECAxESITFhcf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A3xcaI1Nw39LuzLzo57AIL//Z",
  },
  areaLiverpool: {
    src: u("photo-1583847268964-b28dc8f51f92", 1600),
    alt: "A bright Liverpool living room",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMF/8QAHBAAAgICAwAAAAAAAAAAAAAAAQIABAMRITFR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAL/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDZr50Dup0D5qQa4wY8DuIkj//Z",
  },
  areaHills: {
    src: u("photo-1600210491892-03d54c0aaf87", 1600),
    alt: "A Hills District living room with tall arched windows",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMF/8QAGxAAAgMAAwAAAAAAAAAAAAAAAREAAxICEzH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANwHdgA5B6TUl1WD20OIh0kf/9k=",
  },
  areaHawkesbury: {
    src: u("photo-1582289545106-efecf907f21e", 1600),
    alt: "A Hawkesbury room opening to the outlook",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMF/8QAGhAAAgMBAQAAAAAAAAAAAAAAAAECAxEEE//EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDXohX6ztimp6yi6niAA//Z",
  },
  areaCampbelltown: {
    src: u("photo-1593696140826-c58b021acf8b", 1600),
    alt: "A Macarthur living room in a newer build",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQF/8QAGxAAAgEFAAAAAAAAAAAAAAAAABEBAgQTMWH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ANam4UpakozcAKP/2Q==",
  },
  areaSydneyCbd: {
    src: u("photo-1646987916641-1f3c8992daa2", 1600),
    alt: "A Sydney CBD apartment interior",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEE/8QAHhAAAQQBBQAAAAAAAAAAAAAAAAIDERITASIxU5H/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AJiq1Rem+OZMWN3sV6AQf//Z",
  },
  areaInnerWest: {
    src: u("photo-1759139445627-5ce9d5fac8f9", 1600),
    alt: "A period Inner West bedroom with original windows",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAP/xAAcEAACAQUBAAAAAAAAAAAAAAABAgADBBESIWH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFREBAQAAAAAAAAAAAAAAAAAAAAH/2gAMAwEAAhEDEQA/AKtWUoaoXVMAyRurEnJ375EQU4//2Q==",
  },
  areaNorthShore: {
    src: u("photo-1635108197332-54105c0ec888", 1600),
    alt: "A North Shore dining room dressed with sheers",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQF/8QAHBAAAgICAwAAAAAAAAAAAAAAAAIBIgMEBTFB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAQADAAAAAAAAAAAAAAAAAAABETH/2gAMAwEAAhEDEQA/ANNt9EyqsLPRK3I2mvoAYw6f/9k=",
  },
  areaNorthernBeaches: {
    src: u("photo-1585737757692-28c2c33e5d95", 1600),
    alt: "A Northern Beaches room with a coastal outlook",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAaEAADAAMBAAAAAAAAAAAAAAAAAQIDEqEU/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwCxy/HDqekDyQm1p0AJR//Z",
  },
  areaSutherland: {
    src: u("photo-1567805405913-356203d5abe1", 1600),
    alt: "Cockpit cushions on a boat moored in the Shire",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQF/8QAHRAAAQQCAwAAAAAAAAAAAAAAEQABAiEDEgQUMf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A125jSDYzGwX9Us+pvLZ8pN2iIU//2Q==",
  },
} satisfies Record<string, Img>;

/**
 * Hero loop — the client's own clip (IMG_4758): hands fitting a knit cover
 * over a seat shell. Re-encoded to a muted, metadata-stripped 24fps MP4.
 * Portrait framing is intentional; the hero's object-cover crops it to fit.
 */
export const heroVideo = {
  src: "/videos/workroom-loop.mp4",
  poster: {
    src: "/photos/hero-video-poster.jpg",
    alt: "Hands fitting a knit cover over a seat shell in the workroom",
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAASAAoDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAIDBAX/xAAkEAACAgAFAwUAAAAAAAAAAAABAgADBBESEyEFMZEyUVJTof/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQACIv/aAAwDAQACEQMRAD8AxXYenXUcNSU2weGfMEk95TaxP2V/sasBeCR2zHMprX5DzCQa7PM/TaandWetGPuVBnaFdeXoXxCEPcRf/9k=",
  },
} as const;
